name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Build Docker Image
      run: |
        docker build -t my-docker-image:latest .
     
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: my-docker-registry
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker Image to Container Registry
      run: |
        docker tag my-docker-image:latest my-docker-registry/my-docker-image:latest
        docker push my-docker-registry/my-docker-image:latest
