name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Build Docker Image
      run: |
        docker build -t my-docker-image:latest .
     
    - name: Set up Docker Auth
      run: |
        echo "{\"auths\":{\"${DOCKER_REGISTRY}\":{\"username\":\"${DOCKER_USERNAME}\",\"password\":\"${DOCKER_PASSWORD}\",\"email\":\"your-email@example.com\",\"auth\":\"\"}}}" > ~/docker-auth.json
        cat ~/docker-auth.json | docker login --username ${DOCKER_USERNAME} --password-stdin ${DOCKER_REGISTRY}
      env:
        DOCKER_REGISTRY: my-docker-registry
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker Image to Container Registry
      run: |
        docker tag my-docker-image:latest my-docker-registry/my-docker-image:latest
        docker push my-docker-registry/my-docker-image:latest
